### ISSUE TITLE
Change format of property definitions for generate Wikidata triples

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#32] opened 2020-05-12 02:50 UTC
The currently supported file format looks like this:

node1 | label | node2 | data_type
-- | -- | -- | --
P2020008 | label | "attributed to software"@en | string
P2020008 | description | software used to extract information from an article or text fragment |  
P2020013 | label | "vertex in-degree"@en | quantity
P2020013 | description | measure of vertex in degree in a graph

We want it it look like this (data_type is not another column, but instead a label. This makes it so that the properties file is an edge file that can be used in KGTK.

node1 | label | node2
-- | -- | --
P2020001 | label | "text Fragment"@en
P2020001 | description | "text fragment of a scholarly article"@en
P2020001 | data_type | item
P2020008 | label | "attributed to software"@en
P2020008 | description | "software used to extract information from an article or text fragment"@en
P2020008 | data_type | string

**Comment by szeke** [comment] 2020-05-12 02:51
Assigning to @saggu , with help from @rongpenl

**Comment by rongpenl** [comment] 2020-05-12 03:38
I think this is a good point. I can try a quick fix.

**Comment by rongpenl** [comment] 2020-05-12 04:12
With pr #33 ,

`kgtk generate_wikidata_triples -pf officialProps.tsv -dp description --debug < sample.tsv`

where `sample.tsv` is 
```
node1	property	node2	id
P2020001	data_type	item	fakeid
P2020001	label	"text Fragment"@en	fakeid
P2020001	description	"text fragment of a scholarly article"@en	fakeid
P2020008	data_type	string	fakeid
P2020008	label	"attributed to software"@en	faked
P2020008	description	"software used to extract information from an article or text fragment"@en	fakeid

```
(note that I changed the order, otherwise triple generator won't know whether `P2020001` is a pnode or qnode when first encountered as it is memoryless.

will generates the following ttl file

```
wd:P2020001 a wikibase:Property ;
    rdfs:label "text Fragment"@en ;
    schema:description "text fragment of a scholarly article"@en ;
    schema:name "text Fragment"@en ;
    wikibase:claim p:P2020001 ;
    wikibase:directClaim wdt:P2020001 ;
    wikibase:directClaimNormalized wdtn:P2020001 ;
    wikibase:novalue wdno:P2020001 ;
    wikibase:propertyType wikibase:WikibaseItem ;
    wikibase:qualifier pq:P2020001 ;
    wikibase:qualifierValue pqv:P2020001 ;
    wikibase:qualifierValueNormalized pqn:P2020001 ;
    wikibase:reference pr:P2020001 ;
    wikibase:referenceValue prv:P2020001 ;
    wikibase:referenceValueNormalized prn:P2020001 ;
    wikibase:statementProperty ps:P2020001 ;
    wikibase:statementValue psv:P2020001 ;
    wikibase:statementValueNormalized psn:P2020001 ;
    skos:prefLabel "text Fragment"@en .

wd:P2020008 a wikibase:Property ;
    rdfs:label "attributed to software"@en ;
    schema:description "software used to extract information from an article or text fragment"@en ;
    schema:name "attributed to software"@en ;
    wikibase:claim p:P2020008 ;
    wikibase:directClaim wdt:P2020008 ;
    wikibase:directClaimNormalized wdtn:P2020008 ;
    wikibase:novalue wdno:P2020008 ;
    wikibase:propertyType wikibase:String ;
    wikibase:qualifier pq:P2020008 ;
    wikibase:qualifierValue pqv:P2020008 ;
    wikibase:qualifierValueNormalized pqn:P2020008 ;
    wikibase:reference pr:P2020008 ;
    wikibase:referenceValue prv:P2020008 ;
    wikibase:referenceValueNormalized prn:P2020008 ;
    wikibase:statementProperty ps:P2020008 ;
    wikibase:statementValue psv:P2020008 ;
    wikibase:statementValueNormalized psn:P2020008 ;
    skos:prefLabel "attributed to software"@en .
```

**Comment by saggu** [comment] 2020-05-12 20:42
@rongpenl the first part of the issue is pending, I will update the google doc and then close it

**Comment by saggu** [comment] 2020-05-12 21:37
The google sheet is updated, https://docs.google.com/spreadsheets/d/1Dt3X_lvpcU_4GoOWZqP1OjAUKFgiZok1PJBTIT1x418/edit#gid=0

**Closed by saggu** 2020-05-12 21:37 UTC
Labels: enhancement
