### ISSUE TITLE
KGTK Windows10 Installation error - Module fcntl not found

### ISSUE THREAD

**Issue by zef78652** [usc-isi-i2/kgtk#673] opened 2022-10-10 04:52 UTC
Trying to install KGTK on my windows laptop.

Giving the below error when executing "pip --no-cache install -U kgtk"

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\huzef\AppData\Local\Temp\pip-install-8tzld7ct\sh_8ca8a2dc38384db981e86fbe980e0c66\setup.py", line 5, in <module>
          import sh
        File "C:\Users\huzef\AppData\Local\Temp\pip-install-8tzld7ct\sh_8ca8a2dc38384db981e86fbe980e0c66\sh.py", line 37, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by saggu** [comment] 2022-10-10 16:47
Hi @zef78652 ,

KGTK cannot be installed on windows OS natively. Please follow the guidelines in this document https://github.com/usc-isi-i2/kgtk/blob/master/docs/install-with-docker.md to use KGTK on windows via docker.

Thanks ,

**Comment by versant2612** [comment] 2022-10-21 20:34
I'm trying to install using docker but it seems to be freezed


Microsoft Windows [versão 10.0.19044.2130]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\WINDOWS\system32>docker pull uscisii2/kgtk
Using default tag: latest
latest: Pulling from uscisii2/kgtk
1fe172e4850f: Pull complete
a7abea65a547: Pull complete
e17464307151: Pull complete
633a67cbfc32: Pull complete
857b4374174d: Pull complete
c2ddec667481: Pull complete
4888fc9f7869: Downloading [======================================>            ]  738.3MB/963.4MB
c5e45ce4521d: Download complete
6d1d8d2adc13: Downloading [=====================================>             ]  555.6MB/748.8MB
2a3d4b11e1a3: Download complete
535ef4978dd4: Download complete
a0d394a68483: Download complete
eb00cc1730df: Download complete
e53c0c682c6e: Download complete
5fe30d70f24d: Download complete
9e18a1a84082: Downloading
000bcf4583c3: Waiting
**proxyconnect tcp: dial tcp 192.168.65.128:3128: i/o timeout**

C:\WINDOWS\system32>
C:\WINDOWS\system32>
C:\WINDOWS\system32>
C:\WINDOWS\system32>
C:\WINDOWS\system32>
C:\WINDOWS\system32>
C:\WINDOWS\system32>docker pull uscisii2/kgtk
Using default tag: latest
latest: Pulling from uscisii2/kgtk
1fe172e4850f: Pull complete
a7abea65a547: Pull complete
e17464307151: Pull complete
633a67cbfc32: Pull complete
857b4374174d: Pull complete
c2ddec667481: Downloading [==================================>                ]  143.8MB/205.6MB
4888fc9f7869: Downloading [================>                                  ]  312.7MB/963.4MB
c5e45ce4521d: Download complete
6d1d8d2adc13: Downloading [==>                                                ]  41.33MB/748.8MB
2a3d4b11e1a3: Waiting
535ef4978dd4: Waiting
a0d394a68483: Waiting
eb00cc1730df: Waiting
e53c0c682c6e: Waiting
5fe30d70f24d: Waiting
9e18a1a84082: Waiting
000bcf4583c3: Waiting

**Comment by dgarijo** [comment] 2022-10-21 20:41
Hi Veronica,
this looks like a problem in your internet connection. I just tried pulling and it works correctly. The image is quite big, so it takes a few minutes:
```
(base) dgarijo@pop-os:~$ docker pull uscisii2/kgtk:latest
latest: Pulling from uscisii2/kgtk
1fe172e4850f: Already exists 
a7abea65a547: Pull complete 
e17464307151: Pull complete 
633a67cbfc32: Pull complete 
857b4374174d: Pull complete 
c2ddec667481: Pull complete 
4888fc9f7869: Pull complete 
c5e45ce4521d: Pull complete 
6d1d8d2adc13: Pull complete 
2a3d4b11e1a3: Pull complete 
535ef4978dd4: Pull complete 
a0d394a68483: Pull complete 
eb00cc1730df: Pull complete 
e53c0c682c6e: Pull complete 
5fe30d70f24d: Pull complete 
9e18a1a84082: Pull complete 
000bcf4583c3: Pull complete 
Digest: sha256:41811b6feccb32611f99dcba8e67255364e167956a15f0d6e3ecdb14511937c1
Status: Downloaded newer image for uscisii2/kgtk:latest
docker.io/uscisii2/kgtk:latest
(base) dgarijo@pop-os:~$ docker run -it --rm  --user root -e NB_GID=100 -e GEN_CERT=yes -e GRANT_SUDO=yes uscisii2/kgtk:latest /bin/bash
root@9a5c7a9ac7a3:/# kgtk --help
usage: kgtk [options] command [ / command]*

kgtk --- Knowledge Graph Toolkit

positional arguments:
  command
    add-id              Copy a KGTK file, adding ID values.

```

**Comment by dgarijo** [comment] 2022-10-25 20:26
I have not been able to reproduce the issue. So if we get no further response, I suggest closing it.

**Comment by versant2612** [comment] 2022-10-26 03:31
today i successfully installed using docker on windows

**Closed** 2022-10-28 22:16 UTC
Labels: documentation, help wanted
