### ISSUE TITLE
"index graph_1_label_idx already exists" error when I try to reuse the cache file in query the entire Wikidata

### ISSUE THREAD

**Issue by xu94-nlp** [usc-isi-i2/kgtk#563] opened 2021-11-02 16:59 UTC
**Describe the bug**
Hi. Thank you very much for developing such a great tool. I'm trying to use kgtk to query the entire wikidata by following procedures:

1. Download the `latest-all.json.bz2` from WikiData Dump (https://dumps.wikimedia.org/wikidatawiki/entities/)
2. Installed kgtk by the instruction in this repo.
3. building `.tsv` files by 
```bash
kgtk  --debug --timing --progress import-wikidata \
        -i latest-all.json.gz \
        --node nodefile.tsv \
        --edge edgefile.tsv \
        --qual qualfile.tsv \
        --use-mgzip-for-input True \
        --use-mgzip-for-output True \
        --use-shm True \
        --procs 6 \
        --mapper-batch-size 5 \
        --max-size-per-mapper-queue 3 \
        --single-mapper-queue True \
        --collect-results True \
        --collect-seperately True\
        --collector-batch-size 10 \
        --collector-queue-per-proc-size 3 \
        --progress-interval 500000 --fail-if-missing False
```
and create cache files by 
```
kgtk query --input-files nodefile.tsv edgefile.tsv qualfile.tsv --graph-cache ~/kgtk-graph-cache.sqlite3.db
```

After step 3, I think I've built the cache file (`.db` file) in need.

***(Error occurs here) 4.  Do following query and the error occurs***
```bash
$ kgtk query --input-files nodefile.tsv edgefile.tsv qualfile.tsv --graph-cache ~/kgtk-graph-cache.sqlite3.db --match '(x)-[:P1476]->(y)' --return 'x as drama_id, y as drama_name'

index graph_1_label_idx already exists
```
The `index graph_1_label_idx already exists` would not appear if I remove the `--graph-cache` option, but kgtk will try to build another cache file.

I'm wondering 

(1) how should I load the entire Wikidata into KGTK so that I could use `query` option on it? or, is it possible to use kgtk on the entire dump of wikidata?
(2) if so, is it possible to use it in the jupyter notebook? Because I didn't find any explanation in the doc about `ConfigureKGTK(...)` and `ck.configure_kgtk(...)` APIs, which, seems to be critical to configure the kgtk instances.

Thank you very much for your reading.

**Comment by szeke** [comment] 2021-11-02 21:20
Hi, we will document the new ConfigureKGTK class which makes all this easier. A good practice when loading the cache is to use the `--as` option to give a shortcut name to the file, which you can later use as the value for the `-i` option in query.

We are creating a Jupyter notebook with settings for `import-wikidata` to make this easier. If you can wait a couple of days, we will point you to it.

If it works for you, it is good to pick a single or few languages as the files will be smaller and everything will be faster.

**Comment by chalypso** [comment] 2021-11-02 21:58
After step 3 above it says "errors occur here" which could mean that the database is built incompletely and the graph cache is in a corrupted state.  What errors occur there?

Also, could you report the output of the following commands:
```
> kgtk query --graph-cache ~/kgtk-graph-cache.sqlite3.db --show-cache
> sqlite3 ~/kgtk-graph-cache.sqlite3.db 'select * from sqlite_master'
> sqlite3 ~/kgtk-graph-cache.sqlite3.db 'select * from fileinfo'
> sqlite3 ~/kgtk-graph-cache.sqlite3.db 'select * from graphinfo'
```
After this you can also try to do the following and then rerun your query to see if that helps, but something else is going wrong it seems which we should figure out and fix first:
```
> sqlite3 ~/kgtk-graph-cache.sqlite3.db 'drop index graph_1_label_idx'
```
Also please run the query commands with the --debug option so we can see what the system is trying to do.

**Comment by xu94-nlp** [comment] 2021-11-03 04:59
> After step 3 above it says "errors occur here" which could mean that the database is built incompletely and the graph cache is in a corrupted state. What errors occur there?

It's the `index graph_1_label_idx already exists` . I think the graph cache is corrupted, as I deleted it and re-build it use the same command the error vanishes (but due to the deletion I'm not able to reproduce the problem by the following instructions...). 

Thank you very much for your reply and help. Next time if I encounter something wrong I'll submit a report including outputs from the following commands.

> 
> Also, could you report the output of the following commands:
> 
> ```
> > kgtk query --graph-cache ~/kgtk-graph-cache.sqlite3.db --show-cache
> > sqlite3 ~/kgtk-graph-cache.sqlite3.db 'select * from sqlite_master'
> > sqlite3 ~/kgtk-graph-cache.sqlite3.db 'select * from fileinfo'
> > sqlite3 ~/kgtk-graph-cache.sqlite3.db 'select * from graphinfo'
> ```
> 
> After this you can also try to do the following and then rerun your query to see if that helps, but something else is going wrong it seems which we should figure out and fix first:
> 
> ```
> > sqlite3 ~/kgtk-graph-cache.sqlite3.db 'drop index graph_1_label_idx'
> ```
> 
> Also please run the query commands with the --debug option so we can see what the system is trying to do.

**Comment by xu94-nlp** [comment] 2021-11-03 05:03
Thank you very much for your reply!

> Hi, we will document the new ConfigureKGTK class which makes all this easier. A good practice when loading the cache is to use the `--as` option to give a shortcut name to the file, which you can later use as the value for the `-i` option in query.

I had gone through the tutorial notebook and the source code of `KGTK`. 
I think the `--as` command is adding environment variables into the system, and the `file` pamaeter in `ConfigureKGTK(file)` should be a list of the environment variables indicating the absolute path of the `.tsv` files that in use. So I added few lines in my notebook to set up environment variables before calling `ConfigureKGTK`. I don't know if I understand it correctly.

> 
> We are creating a Jupyter notebook with settings for `import-wikidata` to make this easier. If you can wait a couple of days, we will point you to it.
> 
> If it works for you, it is good to pick a single or few languages as the files will be smaller and everything will be faster.

Thank you very much for your help and reply. I'm looking forward to use KGTK for my research in future.

**Comment by chalypso** [comment] 2021-11-03 16:24
bug not reproducible, likely due to some other temporary failure, closing.

**Closed by chalypso** 2021-11-03 16:24 UTC
Labels: bug, priority 1
